version: '3.8'
services:
 backend:
   build: ./spring-petclinic-rest
   image: maven:3.8.4-jdk-8 AS build
   container_name: spring-petclinic-rest
   restart: unless-stopped
   
 db:
    build: ./spring-petclinic-rest/petclinic-db
    image: mysql:5.7
    container_name: petclinic-db
    restart: always
    ports
    environment:
      MYSQL_DATABASE: 'petclinic-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - petclinic-db:/var/lib/mysql
# Names our volume
volumes:
  petclinic-db:

